### ISSUE TITLE
Half baked and ultimately unusable

### ISSUE THREAD

**Issue by thedeanius** [mediasoftpro/videoengine#7]
I have so much I could say here right now,. In fact, I just deleted about 4 paragraphs and decided to say just one thing. 
Write an actual installation guide. With instructions and details that relate to your product. Dumping users onto a generalized MS deployment guide is no good especially when 90% of the info there does not relate to your app.

**Comment by cloudtechpk** [comment]
Hi @thedeanius, what information you are talking about, we will add documentation for every feature that exist but still it's a huge project with hundreds of features. 

This product is part of two core areas ASP.NET Core 3.1 and Angular 9. And both needs separate process while working on it.

Here is product installation that will guide you about installing the ASP.NET Core application. https://www.mediasoftpro.com/docs/documentation/756/aspnet-videoengine-installation 

Here is detail guide regarding working on Angular 9 App (that's part of solution)
https://www.mediasoftpro.com/docs/documentation/768/working-in-angular-application

----------------
This product requires that you have atleast working experience in ASP.NET Core and Angular 2+
----------------
Can you tell about 90% of information? not sure which areas you are talking about.

**Comment by cloudtechpk** [comment]
This issue need to be closed as it have no technical detail or information about issue, just a spam comment. next time be practical, its early release builds, we appreciate if you have feedback.
